### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by adriano-ufrb** [sorecords/true_motion_blur#1]
It is not working here. It renders subframes but the final image is blank.

Blender 2.83

internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.75\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.7833\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.8167\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.85\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.8833\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.9167\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.95\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\5.9833\Image0005.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.0167\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.05\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.0833\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.1167\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.15\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.1833\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.2167\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Saved: C:\_True_Motion_Blur_tmp\Scene\View Layer\0\6.25\Image0006.exr
internal error: modal gizmo-map handler has invalid area
Info: Total Render Time: 0:00:12.004

**Comment by adriano-ufrb** [comment]
Setting a path in the Output solved the issue.

**Comment by sorecords** [comment]
Thank you very much. Now I exactly know where the problem is. In the next commit I'll try to fix it by changing default temporary subframes directory path from render output folder to Blender default temporary folder. It should help.

**Comment by sorecords** [comment]
Fixed for Render Image operator. But still when Render Animation it is better to set exact folder for saving render results in Output Properties -> Output.
